// Generated by https://quicktype.io

import { User } from "src/app/auth/interfaces/user.interface";

export interface DiagramsResponse {
  id:          number;
  name:        string;
  description: string;
  data:        null | string;
  createdAt:   string;
  updatedAt:   null;
  user:        User;
  coWorkers?:   any[];
}


