// Generated by https://quicktype.io

import { User } from "src/app/auth/interfaces/user.interface";

export interface DiagramsResponse {
  id:            number;
  name:          string;
  description:   string;
  data:          string;
  createdAt:     string;
  updatedAt:     string;
  collaborators?: Collaborator[];
  user:          User;
}

export interface Collaborator {
  id:   number;
  user: User;
}


